In [ ]:
#Accessing the elements in a tensor

''' Tensor [row, column ]'''

import torch

In [ ]:
tensor=torch.tensor([[10,20,30],[40,50,60],[70,80,90]])
print(tensor.ndim)
print(tensor.shape)

2
torch.Size([3, 3])


In [ ]:
print("Element at (0,1):", tensor[0,1])

Element at (0,1): tensor(20)


In [ ]:
#First Row
print("Tensor present at 0", tensor[0])


Tensor present at 0 tensor([10, 20, 30])


In [ ]:
#Access first column
print("First Column", tensor[:,0])

First Column tensor([10, 40, 70])


Slicing


In [ ]:
print(tensor)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [ ]:
print("First two rows: ", tensor[:2])

First two rows:  tensor([[10, 20, 30],
        [40, 50, 60]])


In [ ]:
print("First two rows: ", tensor[:,:2])

First two rows:  tensor([[10, 20],
        [40, 50],
        [70, 80]])


In [ ]:
#Middle elements (row1, column 1 and 2 only)
print(tensor[1,1:3])


tensor([50, 60])


In [ ]:
print(tensor[:2:3])

tensor([[10, 20, 30]])


In [ ]:
second_elements = tensor[:, 1]
print(second_elements)

tensor([20, 50, 80])


In [ ]:
#Fancy Indexing : Trying to Access 20 and 90

tensor[[0,2],[1,2]]

tensor([20, 90])

In [ ]:
 #Boolean Indexing

 mask= tensor>50
 print(mask)
 print(tensor[mask])

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([60, 70, 80, 90])


In [ ]:
#changing tensor values via indexing
print(tensor)
tensor[0,1]=25
print(tensor)

tensor([[10, 25, 30],
        [40, 50, 60],
        [70, 80, 90]])
tensor([[10, 25, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [ ]:
tensor[:,0]= torch.tensor([100,200,300])
print(tensor)

tensor([[100,  25,  30],
        [200,  50,  60],
        [300,  80,  90]])


In [ ]:
indices= torch.tensor([0,2])
selected_rows=torch.index_select(tensor,dim=0,index= indices)
print(selected_rows)


'''torch.index_select() lets you select specific rows (or columns) by index.

dim=0 → rows, dim=1 → columns

index=indices is a tensor of indices you want to pick.'''
#dim 0 => Rows
#dim 1 => Column

tensor([[100,  25,  30],
        [300,  80,  90]])


'torch.index_select() lets you select specific rows (or columns) by index.\n\ndim=0 → rows, dim=1 → columns\n\nindex=indices is a tensor of indices you want to pick.'

In [ ]:
#using tensor with steps

print(tensor[:,::2])

tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [ ]:
torch.flip(tensor, dims=(0,))


tensor([[300,  80,  90],
        [200,  50,  60],
        [100,  25,  30]])