

## ✅ **1. `.view()`**

### 🔹 Description:

* Changes the **shape** of the tensor **without copying the data**.
* Only works on **contiguous** tensors (data must be laid out linearly in memory).

### ❗ If the tensor is **not contiguous**, `.view()` will raise an error:

```python
RuntimeError: view size is not compatible with input tensor's size and stride...
```

### ✅ Use `.view()` when:

* You **know** the tensor is **contiguous** (e.g., freshly created or `.contiguous()` was called).
* You want to **avoid unnecessary memory copies** for performance reasons.

---

## ✅ **2. `.reshape()`**

### 🔹 Description:

* Changes the **shape** of the tensor.
* Works on **both contiguous and non-contiguous** tensors.
* Will **copy memory** if required to make the reshape possible.

### ✅ Use `.reshape()` when:

* You’re not sure whether the tensor is contiguous.
* You want a **safer and more flexible** operation.
* You’re okay with a **possible memory copy** for convenience.

---

## 🧪 Example Comparison:

```python
x = torch.randn(2, 3, 4)
x_transposed = x.permute(1, 0, 2)  # non-contiguous

x_transposed.view(6, 4)       # ❌ RuntimeError
x_transposed.contiguous().view(6, 4)  # ✅ Works
x_transposed.reshape(6, 4)    # ✅ Works (auto-handles contiguity)
```

---

## 📊 Summary Table

| Feature              | `.view()`                      | `.reshape()`                    |
| -------------------- | ------------------------------ | ------------------------------- |
| Requires contiguous? | ✅ Yes                          | ❌ No                            |
| Can copy memory?     | ❌ No                           | ✅ Yes (if needed)               |
| Safe for any tensor? | ❌ No                           | ✅ Yes                           |
| Performance          | ⚡ Faster (no copy)             | Slightly slower (may copy)      |
| Recommended when     | You need speed and know layout | You need flexibility and safety |

---

## ✅ Best Practice

> 🔹 Use `.view()` when you're sure the tensor is **contiguous** (e.g., after `.contiguous()`).
> 🔹 Use `.reshape()` for **general-purpose** reshaping, especially with **transposed or permuted tensors**.




In [ ]:
import torch

In [ ]:
tensor=torch.arange(12)

In [ ]:
reshaped_tensor_view=tensor.view(2,6)
reshaped_tensor_reshape=tensor.reshape(2,6)
print(reshaped_tensor_view)
print(reshaped_tensor_reshape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [ ]:
tensor.is_contiguous()

True

In [ ]:
inferred_shape= tensor.view(3,-1) #-1 pytorch will take the value by itself
print(inferred_shape)
print(inferred_shape.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [ ]:
tensor3d=torch.arange(24).reshape(2,3,4)
print(tensor3d)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [ ]:
flattened=tensor3d.view(-1)
print(flattened)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])


In [ ]:
flattened.is_contiguous()

True

In [ ]:
tensor2d=torch.arange(24).reshape(12,2)
transposed_tensor=tensor2d.t()

In [ ]:
transposed_tensor.is_contiguous()

False

In [ ]:
transposed_tensor.view(6,4)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [ ]:
transposed_tensor.reshape(6,4)

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])

In [ ]:
contiguous=transposed_tensor.contiguous()
error=contiguous.view(6,4)